es1)
SELECT Cognome
FROM IMPIEGATO
JOIN DIPARTIMENTO on IMPIEGATO.CodDip = DIPARTIMENTO.CodDip
WHERE Città = 'Torino'
ORDER BY Cognome;

es2)
SELECT *
FROM TURNO
JOIN TURNO.CodImp = IMPIEGATO.CodImp
JOIN  IMPIEGATO.CodDip = DIPARTIMENTO.CodDip
WHERE Stipendio > 1000 AND Città = 'Verona';

es3)
SELECT MAX(Stipendio) AS MaxStipendio
FROM IMPIEGATO
WHERE Città = 'Milano';

es4)
SELECT DIPARTIMENTO.CodDip, AVG(IMPIEGATO.Stipendio) AS StipendioMedio
FROM IMPIEGATO
JOIN DIPARTIMENTO ON IMPIEGATO.CodDip = DIPARTIMENTO.CodDip
GROUP BY DIPARTIMENTO.CodDip;

es5)
SELECT DIPARTIMENTO.CodDip, DIPARTIMENTO.Denominazione
FROM IMPIEGATO
JOIN DIPARTIMENTO ON IMPIEGATO.CodDip = DIPARTIMENTO.CodDip
HAVING SommaStipendi > 100000;

es6)
SELECT DIPARTIMENTO.Denominazione
FROM IMPIEGATO
JOIN DIPARTIMENTO ON IMPIEGATO.CodDip = DIPARTIMENTO.CodDip
HAVING COUNT(IMPIEGATO.CodImp) > 100;

es7)
SELECT DIPARTIMENTO.Città, COUNT(IMPIEGATO.CodImp) AS NumeroImpiegati
FROM IMPIEGATO
JOIN IMPIEGATO.CodDip = DIPARTIMENTO.CodDip


es8)
SELECT DIPARTIMENTO.Città, DIPARTIMENTO.CodDip, COUNT(IMPIEGATO.CodImp) AS NumeroImpiegati
JOIN DIPARTIMENTO ON IMPIEGATO.CodDip = DIPARTIMENTO.CodDip
HAVING NumeroImpiegati > 100;