SELECT Targa, Marca
FROM AUTO
WHERE Cilindrata > 2000 OR Potenza > 120;

SELECT Targa
FROM AUTO
WHERE Potenza = (SELECT MAX(Potenza) FROM AUTO);

SELECT AUTO.Targa, PROPRIETARI.Nome
FROM AUTO
JOIN PROPRIETARI ON AUTO.CodF = PROPRIETARI.CodF
JOIN ASSICURAZIONI ON AUTO.CodAss = ASSICURAZIONI.CodAss

SELECT Marca, MAX(Cilindrata)
FROM AUTO
GROUP BY Marca;

SELECT AUTOCOINVOLTE.Targa, COUNT(*)
FROM AUTOCOINVOLTE
JOIN AUTO ON AUTOCOINVOLTE.Targa = AUTO.Targa
WHERE AUTO.Marca = 'Fiat'
GROUP BY AUTOCOINVOLTE.Targa;

SELECT AUTOCOINVOLTE.Targa, ASSICURAZIONI.Nome, SUM(AUTOCOINVOLTE.ImportoDelDanno)
FROM AUTOCOINVOLTE
JOIN AUTO ON AUTOCOINVOLTE.Targa = AUTO.Targa
JOIN ASSICURAZIONI ON AUTO.CodAss = ASSICURAZIONI.CodAss
GROUP BY AUTOCOINVOLTE.Targa, ASSICURAZIONI.Nome;